services:
  sagemath:
    image: sagemath/sagemath:latest
    container_name: sagemath
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/sage/notebooks
    command: >
      sage -n jupyterlab --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.notebook_dir='/home/sage/notebooks'
    platform: linux/amd64

